#region Profiling
	global.debug_overlay = false
#endregion

#region Console
	global.console = false
	global.console_buffer = false
	
	// Initialize the console log now if anything prior to this script hasn't sent
	// any debug messages
	if not variable_global_exists("console_log") {
		global.console_log = ds_list_create()
	}
	
	global.console_input_previous = ""
#endregion

#region Exception Handling
	exception_unhandled_handler(function (e) {
		var exception_json = json_stringify(e, true)
	
	    print("!!! ------------------------------------------------------- !!!")
	    print("Unhandled exception!")
		print(exception_json)
	    print("!!! ------------------------------------------------------- !!!")
	
	    var filename = console_save("crash/crash", "This log was automatically generated by a crash.\n\n" + exception_json)
	
	    if show_question(string(@"PNEngine has crashed.
	A crash log including the details has been saved to {0}.

	The error was:
	{1}

	Do you want to copy the error to the clipboard?", filename, e.longMessage)) {
			clipboard_set_text(exception_json)
			show_message("The error has been copied to the clipboard.")
		}
	
	    return 0
	})
#endregion